name: nf-var
channels:
  - bioconda
  - conda-forge
dependencies:
  - samtools=1.19.2
  - bcftools=1.19
  - pandas=2.1.1
  - numpy=1.26.3
  - seaborn=0.13.2
  - biopython=1.83
  - vcflib=1.0.3 # Note the most recent version: 1.0.6 yields an error. When installing 1.0.3 I also needed to downgrade to tabixpp==1.1.0
  - freebayes=1.3.6